version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      BETTER_AUTH_URL: http://localhost:3000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/workout-tracker
      REDIS_URL: redis://redis:6379
      PORT: 3000
      TZ: America/Sao_Paulo
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      migrate:
        condition: service_completed_successfully

  migrate:
    image: oven/bun
    container_name: migrate
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/workout-tracker
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Rodando migrações...' &&
        bun install &&
        bunx drizzle-kit push &&
        echo 'Migrações concluídas!'
      "

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workout-tracker
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d workout-tracker"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: